"""Порты — интерфейсы, через которые сервисы говорят с внешним миром.

Смысл в направлении зависимостей: сервис объявляет, что ему нужно («уметь
коммитить», «уметь перезапускать юнит»), а инфраструктура под это подстраивается.
Поэтому здесь Protocol, а не абстрактные классы: реализация не обязана знать
о существовании порта, ей достаточно совпасть по сигнатурам, и в тестах можно
подсунуть простую заглушку без наследования.

Кто во что превращается — прописано в app/di.py, это единственное место, где
порт встречается со своей реализацией.
"""
from __future__ import annotations

from collections.abc import Awaitable, Callable, Sequence
from datetime import datetime
from pathlib import Path
from typing import Any, Protocol, runtime_checkable

from .dto import LLMReply, TurnOutcome
from .models import (Chunk, Deployment, Event, Fact, Goal, GoalStep, Note,
                     Reminder, SttTerm, Turn)


# --------------------------------------------------------------------------- #
#  хранилище
# --------------------------------------------------------------------------- #
class DeploymentRepository(Protocol):
    """История выкаток. Отвечает на «что мы катили и чем это кончилось»."""

    async def add(self, deployment: Deployment) -> Deployment: ...
    async def update(self, deployment: Deployment) -> None: ...
    async def get(self, deployment_id: int) -> Deployment | None: ...
    async def by_sha(self, sha: str) -> Deployment | None: ...
    async def in_flight(self) -> Deployment | None:
        """Незакрытая выкатка, если она есть: две сразу запускать нельзя."""
        ...
    async def recent(self, limit: int = 20) -> list[Deployment]: ...


class TurnRepository(Protocol):
    """Журнал ходов — моя собственная память о том, что тут происходило."""

    async def add(self, turn: Turn) -> Turn: ...
    async def search(self, query: str, limit: int = 10) -> list[tuple[Turn, float]]:
        """Поиск по тексту вопроса и ответа. float — релевантность."""
        ...
    async def recent(self, limit: int = 10) -> list[Turn]: ...
    async def by_ids(self, ids: Sequence[int]) -> dict[int, Turn]:
        """Ходы по списку id — чтобы поиск по кускам показал их целиком."""
        ...

    async def stats(self) -> dict[str, Any]:
        """Сводка: сколько ходов, сколько денег, когда был первый."""
        ...

    # Семантика: пока эмбеддера нет, эти методы просто никто не зовёт.
    async def pending_embeddings(self, model: str, limit: int = 100) -> list[tuple[int, str]]: ...
    async def set_embedding(self, turn_id: int, vector: list[float], model: str) -> None: ...
    async def search_semantic(self, vector: list[float], model: str,
                              limit: int = 10) -> list[tuple[Turn, float]]: ...
    async def embedding_stats(self, model: str) -> dict[str, int]: ...


class NoteRepository(Protocol):
    """Заметки себе. Отдельно от ходов: ход — это факт, заметка — вывод."""

    async def add(self, note: Note) -> Note: ...
    async def search(self, query: str, limit: int = 10) -> list[Note]: ...
    async def recent(self, limit: int = 10) -> list[Note]: ...
    async def delete(self, note_id: int) -> bool: ...
    async def pending_embeddings(self, model: str, limit: int = 100) -> list[tuple[int, str]]: ...
    async def set_embedding(self, note_id: int, vector: list[float], model: str) -> None: ...
    async def search_semantic(self, vector: list[float], model: str,
                              limit: int = 10) -> list[Note]: ...


class TermRepository(Protocol):
    """Живой словарь терминов распознавания."""

    async def add(self, term: SttTerm) -> SttTerm: ...
    async def remove(self, variant: str) -> bool: ...
    async def all(self) -> list[SttTerm]: ...


class GoalRepository(Protocol):
    """Цели, к которым бот идёт сам, и журнал продвижения к ним."""

    async def add(self, goal: Goal) -> Goal: ...
    async def due(self, now: datetime, limit: int = 5) -> list[Goal]: ...
    async def get(self, goal_id: int) -> Goal | None: ...
    async def update(self, goal: Goal) -> None: ...
    async def active(self, chat_id: int) -> list[Goal]: ...
    async def add_step(self, step: GoalStep) -> GoalStep: ...
    async def recent_steps(self, goal_id: int, limit: int = 8) -> list[GoalStep]: ...


class ReminderRepository(Protocol):
    """Обязательства и напоминания — то, из-за чего бот заговорит сам."""

    async def add(self, reminder: Reminder) -> Reminder: ...
    async def due(self, now: datetime, limit: int = 20) -> list[Reminder]:
        """Всё, чему пришёл срок и что ещё не закрыто."""
        ...
    async def get(self, reminder_id: int) -> Reminder | None: ...
    async def update(self, reminder: Reminder) -> None: ...
    async def open_items(self, chat_id: int, limit: int = 50) -> list[Reminder]: ...
    async def recently_done(self, chat_id: int, limit: int = 10) -> list[Reminder]: ...


class ChunkRepository(Protocol):
    """Куски записей — единица поиска по памяти.

    rebuild перестраивает нарезку записи целиком (удалить и вставить заново), а
    не досыпает куски: иначе исправленный ответ оставил бы в индексе обрывки
    прежней версии, и поиск находил бы то, чего уже нет.
    """

    async def rebuild(self, source_kind: str, source_id: int,
                      created_at: datetime, pieces: Sequence[tuple[str, str]]) -> int: ...
    async def sources_without_chunks(self, source_kind: str,
                                     limit: int = 50) -> list[int]: ...
    async def pending_embeddings(self, model: str, limit: int = 100) -> list[tuple[int, str]]: ...
    async def set_embedding(self, chunk_id: int, vector: list[float], model: str) -> None: ...
    async def search_text(self, query: str, limit: int = 20) -> list[tuple[Chunk, float]]: ...
    async def search_semantic(self, vector: list[float], model: str,
                              limit: int = 20) -> list[tuple[Chunk, float]]: ...
    async def stats(self, model: str) -> dict[str, int]: ...


class FactRepository(Protocol):
    """Факты. Обратите внимание: удаления нет, есть retire.

    Факт не стирают, а закрывают датой — иначе теряется возможность понять
    старую переписку, где он ещё действовал.
    """

    async def add(self, fact: Fact) -> Fact: ...
    async def get(self, fact_id: int) -> Fact | None: ...
    async def active(self, subject: str | None = None, limit: int = 200) -> list[Fact]: ...
    async def pinned(self, limit: int = 60) -> list[Fact]: ...
    async def search(self, query: str, limit: int = 10,
                     include_retired: bool = False) -> list[Fact]: ...
    async def retire(self, fact_id: int, superseded_by: int | None = None) -> bool:
        """Закрыть факт текущим временем. Возвращает False, если он уже закрыт."""
        ...

    async def history(self, subject: str, key: str, limit: int = 20) -> list[Fact]:
        """Все версии одного ключа, свежие первыми."""
        ...


class EventRepository(Protocol):
    """События. Главный способ спросить — диапазон дат, а не текст."""

    async def add(self, event: Event) -> Event: ...
    async def get(self, event_id: int) -> Event | None: ...
    async def between(self, start: datetime, end: datetime,
                      limit: int = 50) -> list[Event]: ...
    async def search(self, query: str, limit: int = 10) -> list[Event]: ...
    async def count(self) -> int: ...
    async def delete(self, event_id: int) -> bool: ...


class KeyValueRepository(Protocol):
    """Мелкое состояние между перезапусками: id сессии, cwd, модель.

    Раньше это был state.json. В БД надёжнее (атомарность, история изменений),
    но файл остаётся резервом на случай, когда БД недоступна, — см. KeyValueStore.
    """

    async def get(self, key: str) -> str | None: ...
    async def set(self, key: str, value: str) -> None: ...
    async def all(self) -> dict[str, str]: ...


# --------------------------------------------------------------------------- #
#  внешние системы
# --------------------------------------------------------------------------- #
class VersionControl(Protocol):
    """git. Ровно те операции, которые нужны самодопилу, и ни одной лишней."""

    def head(self) -> str: ...
    def short(self, ref: str) -> str: ...
    def subject(self, ref: str) -> str: ...
    def resolve(self, ref: str) -> str: ...
    def dirty(self) -> list[tuple[str, str]]:
        """[(статус, путь)] по отслеживаемым каталогам."""
        ...
    def commit(self, message: str, paths: Sequence[str]) -> str: ...
    def tag(self, name: str, ref: str) -> None: ...
    def tag_sha(self, name: str) -> str | None: ...
    def log(self, limit: int) -> list[dict[str, str]]: ...
    def reset_hard(self, ref: str) -> None: ...


class ServiceControl(Protocol):
    """systemd: перезапустить себя и вынести сторожа за пределы своего cgroup."""

    def restart(self, unit: str) -> None: ...
    def is_active(self, unit: str) -> bool: ...
    def spawn_detached(self, name: str, argv: Sequence[str]) -> str: ...


class AssistantProcess(Protocol):
    """Процесс `claude --print --input-format stream-json` — мой собственный мозг.

    Живёт долго, переживает ходы, умеет резюмировать сессию по id. Порт нужен,
    чтобы ConversationService можно было тестировать без запуска настоящего claude.
    """

    @property
    def alive(self) -> bool: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def restart(self, *, fresh: bool = False) -> None: ...
    async def ask(self, text: str, on_event: Callable[[dict], Awaitable[None]]) -> dict: ...
    async def interrupt(self, timeout: float = 15.0) -> bool: ...
    def status(self) -> dict[str, Any]: ...
    def context_usage(self) -> tuple[int, int]: ...
    def set_cwd(self, path: Path) -> None:
        """Сменить рабочую директорию. Применится при следующем запуске процесса."""
        ...
    def set_model(self, name: str) -> None: ...


class SpeechToText(Protocol):
    """Распознавание голосовых: Groq, если есть ключ, иначе локальный whisper."""

    async def transcribe(self, path: Path) -> str: ...
    def backend_name(self) -> str: ...


@runtime_checkable
class Embedder(Protocol):
    """Векторизация текста для семантического поиска.

    Отдельный порт от LLMClient: эмбеддинги — другой протокол (свой эндпоинт,
    батчи, размерность) и, вообще говоря, другой провайдер. Сейчас за обоими
    портами стоит OpenRouter, но увести векторы к кому-то ещё должно быть можно,
    не трогая чат-модель.

    Без ключа в контейнере стоит NullEmbedder: он честно говорит «не умею», и
    поиск по журналу вырождается в полнотекстовый.
    """

    def available(self) -> bool: ...
    def dimensions(self) -> int:
        """Длина вектора. Должна совпадать с типом колонки в БД."""
        ...
    def model_name(self) -> str: ...
    async def embed(self, texts: Sequence[str]) -> list[list[float]]: ...


class LLMClient(Protocol):
    """Языковая модель общего назначения — для вспомогательных задач.

    Это не тот claude, что ведёт разговор: тот живёт отдельным процессом и держит
    контекст. Здесь — короткие служебные вызовы без истории: подсказать, что
    услышалось в кривой расшифровке, сжать длинный ход в одну строку, разметить
    заметку. Порт нарочно провайдер-независимый: сегодня за ним OpenRouter,
    завтра что угодно другое.
    """

    def available(self) -> bool: ...
    def default_model(self) -> str: ...
    async def complete(self, prompt: str, *, system: str | None = None,
                       model: str | None = None, max_tokens: int = 1024,
                       temperature: float = 0.2) -> LLMReply: ...


class Notifier(Protocol):
    """Разговор с чатом со стороны сервиса.

    Нужен тем, кто говорит сам, без входящего апдейта: ход из очереди завершился,
    процесс claude умер, выкатка доехала. Через порт — чтобы сервис не знал ни
    про aiogram, ни про HTML-разметку сообщений.
    """

    async def send(self, chat_id: int, html: str) -> None: ...
    async def send_error(self, chat_id: int, title: str, detail: str) -> None:
        """Сообщить о сбое. Экранирование текста — забота реализации."""
        ...
    async def send_actions(self, chat_id: int, html: str,
                           actions: list[tuple[str, str]]) -> object:
        """Сообщение с кнопками: всё, что бот шлёт сам, должно закрываться касанием."""
        ...
    async def typing(self, chat_id: int) -> None: ...
    async def alive(self) -> bool:
        """Отвечает ли Telegram. Нужно пульсу: бот, который не может ответить,
        здоровым не считается."""
        ...


class TurnPresenter(Protocol):
    """Показ одного хода: живое сообщение во время работы, разбор в конце.

    Отдельный порт нужен, чтобы ConversationService не зависел от Telegram.
    Он решает, что ход состоялся; как это выглядит на экране — не его дело.
    """

    async def start(self) -> None: ...
    async def on_event(self, event: dict) -> None: ...
    async def finish(self, result: dict) -> None: ...
    def close(self) -> None: ...
    @property
    def answer(self) -> str: ...
    @property
    def tools(self) -> list[str]: ...


class TurnPresenterFactory(Protocol):
    """Создатель презентеров: на каждый ход — свой."""

    def create(self, chat_id: int, reply_to: int | None) -> TurnPresenter: ...


class LogReader(Protocol):
    """Чтение собственных логов.

    Нужен, чтобы посмотреть, что происходило, прямо из чата — не заходя по SSH.
    Порт, а не прямая работа с файлами, по обычной причине: сервис не должен
    знать, лежит лог файлом, в journald или где-то ещё.
    """

    def streams(self) -> list[str]: ...
    def tail(self, stream: str, limit: int, needle: str | None = None) -> list[str]: ...
    def path(self, stream: str) -> Path | None: ...
    def size(self, stream: str) -> int: ...


class StorageHealth(Protocol):
    """Живо ли хранилище. Минимальный контракт: пульсу больше ничего не нужно."""

    async def healthy(self) -> bool: ...
